name: webviewx
description: A feature-rich cross-platform webview using webview_flutter for
  mobile and iframe for web. JS interop-ready.
homepage: https://github.com/adrianflutur/webviewx
version: 0.2.2

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  path:
  pointer_interceptor:
  uuid: ^4.0.4
  webview_flutter: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.6.0
